@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "roteiro8.parte6.SistemaEstoqueAdapterSAP",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_995410012 { 
   	label=parte6
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   AdapterFactory852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AdapterFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   sistemacontabilAdapter: SistemaContabilAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sistemaestoqueAdapter: SistemaEstoqueAdapter [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ criarSistemaContabilAdapter(nome: String): SistemaContabilAdapter</TD></TR>
<TR><TD ALIGN="LEFT" >+ criarSistemaEstoqueAdapter(nome: String): SistemaEstoqueAdapter</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ControladorContabil852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ControladorContabil</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   factory: AdapterFactory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sistemacontabilAdapter: SistemaContabilAdapter [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calcularImposto()</TD></TR>
<TR><TD ALIGN="LEFT" >+ criarSistemaContabilAdapter(nome: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ControladorEstoque852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ControladorEstoque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   factory: AdapterFactory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sistemaestoqueAdapter: SistemaEstoqueAdapter [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ aumentarQuantidadeItem()</TD></TR>
<TR><TD ALIGN="LEFT" >+ criarSistemaEstoqueAdapter(nome: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ diminuirQuantidadeItem()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ControladorRegistradora852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ControladorRegistradora</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   factory: AdapterFactory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sistemacontabilAdapter: SistemaContabilAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sistemaestoqueAdapter: SistemaEstoqueAdapter [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ criarSistemaContabilAdapter(nome: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ criarSistemaEstoqueAdapter(nome: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ diminuirQuantidadeItem()</TD></TR>
<TR><TD ALIGN="LEFT" >+ registrarVendaSistemaContabil()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SistemaEstoque852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SistemaEstoque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ adicionarItemEstoque()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removerItemEstoque()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SistemaEstoqueAdapter852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SistemaEstoqueAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   sistemaEstoque: SistemaEstoque [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ aumentarQuantidadeItem()</TD></TR>
<TR><TD ALIGN="LEFT" >+ diminuirQuantidadeItem()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SistemaEstoqueAdapterDELL852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SistemaEstoqueAdapterDELL</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   sistemaEstoque: SistemaEstoque [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SistemaEstoqueAdapterIBM852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SistemaEstoqueAdapterIBM</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   sistemaEstoque: SistemaEstoque [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SistemaEstoqueAdapterSAP852391506[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SistemaEstoqueAdapterSAP</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   sistemaEstoque: SistemaEstoque [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_995410017 { 
   	label=parte1
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   SistemaEstoque852391501[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SistemaEstoque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ adicionarItemEstoque()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removerItemEstoque()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
AdapterFactory852391506 -> SistemaEstoqueAdapter852391506[label="sistemaestoqueAdapter
[0..1]"];
ControladorContabil852391506 -> AdapterFactory852391506[label="factory
[0..1]"];
ControladorEstoque852391506 -> AdapterFactory852391506[label="factory
[0..1]"];
ControladorEstoque852391506 -> SistemaEstoqueAdapter852391506[label="sistemaestoqueAdapter
[0..1]"];
ControladorRegistradora852391506 -> AdapterFactory852391506[label="factory
[0..1]"];
ControladorRegistradora852391506 -> SistemaEstoqueAdapter852391506[label="sistemaestoqueAdapter
[0..1]"];
SistemaEstoqueAdapter852391506 -> SistemaEstoque852391506[label="sistemaEstoque
[0..1]"];
SistemaEstoqueAdapter852391506 -> SistemaEstoqueAdapterDELL852391506[arrowhead=none, arrowtail=empty, dir=both];
SistemaEstoqueAdapter852391506 -> SistemaEstoqueAdapterIBM852391506[arrowhead=none, arrowtail=empty, dir=both];
SistemaEstoqueAdapter852391506 -> SistemaEstoqueAdapterSAP852391506[arrowhead=none, arrowtail=empty, dir=both];
SistemaEstoqueAdapterDELL852391506 -> SistemaEstoque852391501[label="sistemaEstoque
[0..1]"];
SistemaEstoqueAdapterIBM852391506 -> SistemaEstoque852391506[label="sistemaEstoque
[0..1]"];
SistemaEstoqueAdapterSAP852391506 -> SistemaEstoque852391506[label="sistemaEstoque
[0..1]"];
    
}
@enduml