@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "roteiro7.parte3.TesteHeranca",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_995410015 { 
   	label=parte3
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Component890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Component</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Container890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Container</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(c: Component)</TD></TR>
<TR><TD ALIGN="LEFT" >+ dispose()</TD></TR>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(c: Component)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FlowContainer890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FlowContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   elements: List&lt;Component&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(c: Component)</TD></TR>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(c: Component)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FlowContainerBordaPontilhada890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FlowContainerBordaPontilhada</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FlowContainerBordaSolida890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FlowContainerBordaSolida</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GridContainer890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GridContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   ColumnMax: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   columnCounter: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   elements: Component[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   lineCounter: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   lineMax: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(c: Component)</TD></TR>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(c: Component)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GridContainerBordaPontilhada890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GridContainerBordaPontilhada</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GridContainerBordaSolida890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GridContainerBordaSolida</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ doLayout()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TesteHeranca890418832[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TesteHeranca</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Container890418832 -> FlowContainer890418832[arrowhead=none, arrowtail=empty, dir=both];
Container890418832 -> GridContainer890418832[arrowhead=none, arrowtail=empty, dir=both];
FlowContainer890418832 -> Component890418832[label="elements
[0..*]"];
FlowContainer890418832 -> FlowContainerBordaPontilhada890418832[arrowhead=none, arrowtail=empty, dir=both];
FlowContainer890418832 -> FlowContainerBordaSolida890418832[arrowhead=none, arrowtail=empty, dir=both];
FlowContainerBordaPontilhada890418832 -> Container890418832[label="doLayout() -> dispose()"];
FlowContainerBordaSolida890418832 -> Container890418832[label="doLayout() -> dispose()"];
GridContainer890418832 -> Component890418832[label="elements
[0..*]"];
GridContainer890418832 -> GridContainerBordaPontilhada890418832[arrowhead=none, arrowtail=empty, dir=both];
GridContainer890418832 -> GridContainerBordaSolida890418832[arrowhead=none, arrowtail=empty, dir=both];
GridContainerBordaPontilhada890418832 -> Container890418832[label="doLayout() -> dispose()"];
GridContainerBordaSolida890418832 -> Container890418832[label="doLayout() -> dispose()"];
    
}
@enduml